# -*- coding: utf-8 -*-
"""programa.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1log30GAKVFfdANC0aP5jZtWiIhIhI0Fb
"""

# Función para convertir grados Celsius a grados Fahrenheit
def celsius_a_fahrenheit(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

# Solicitar al usuario la temperatura en grados Celsius
celsius = float(input("Ingresa la temperatura en grados Celsius: "))

# Calcular la temperatura en grados Fahrenheit
fahrenheit = celsius_a_fahrenheit(celsius)

# Mostrar el resultado
print(f"{celsius} grados Celsius son equivalentes a {fahrenheit} grados Fahrenheit.")